### PR TITLE
Python3 updates

### PR DESCRIPTION
**Pull request by dagorym**
This is the update for the FermiTools to use Python 3.  This PR should also include a merge of the python3_updates branch on the following repositories.  This merge has been tested on the separate python3_updates branch and the build has been validated on the following pipeline job: https://dev.azure.com/FermiSpaceTelescope/Fermitools/_build/results?buildId=745&view=results

The test scripts on that job failed as they have not been updated for Python 3 yet.  There is an outstanding PR for that update: https://github.com/fermi-lat/test-scripts/pull/2.  That PR should be finished and the conda test-script package updated before the PR occurs.

The other repos affected by this PR are:
- [ ] astro
- [ ] BayesianBlocks
- [ ] celestialSources
- [ ] embed_python
- [ ] evtUtils
- [ ] facilities
- [ ] fitsGen
- [ ] flux
- [ ] irfs
- [ ] modelEditor
- [ ] observationSim
- [ ] optimizers
- [ ] pointlike
- [ ] pyBurstAnalysisGUI
- [ ] pyLikelihood
- [ ] sane
- [ ] ScienceTools
- [ ] SConsShared
- [ ] skymaps
- [ ] st_graph
- [ ] top
- [ ] xmlBase

### CODE REVIEW

**Comment by aurelio-amerio** [comment]
Hello, is there an ETA for this pull request to be merged? Thank you very much for your hard work and wonderful project!

**Comment by jasercion** [comment]
@aurelio-amerio We actually are currently testing a build with these changes.  If you'd like to try out this beta you can do so using the command

`conda install -c conda-forge -c fermi -c fermi/label/beta fermitools=1.9.13`

However, since this is a beta we cannot provide support for this build.  But we welcome any bug reports you may have!

**Comment by aurelio-amerio** [comment]
@jasercion thank you very much! I will try it!

**Comment by jasercion** [comment]
@aurelio-amerio Forgot to point out, you should install this into a separate testing environment to make sure you don't run into dependency conflicts.

**Pull request merged**
